### ISSUE TITLE
Unable to use browse for an icon in a program launcher 

### ISSUE THREAD

**Issue by AlanAtOpcug** [linuxmint/mint21-beta#53] opened 2022-07-15 18:50 UTC
Mint 21, Cinnamon
When creating a program launcher, or using the Properties function in an established launcher, browsing for an icon results in the loading process never completing.
Steps for an established program launcher trying to locate an image on a disk partition:
1. Right-click on program launcher
2. Navigate to Properties – Icon – Browse – Other Locations – DataDisk – nikon – desktop_images – restart.png – Open 
3. Dialogue window indicates "Loading"
The selected icon is never loaded and the "circle" icon just keeps spinning
This issue always occurs with Mint 21
This was not an issue in Mint 20.3

**Comment by spamegg1** [comment] 2022-07-15 18:54
Duplicate of #9 #17 #45 ?

**Closed** 2022-07-15 19:15 UTC
