### ISSUE TITLE
cinnamon: Brightness OSD doesn't show on primary display

### ISSUE THREAD

**Issue by mantuoliveira** [linuxmint/mint21-beta#121] opened 2022-07-19 22:26 UTC
**Describe the bug**

The screen brightness level is always shown on the external monitor even though the notebook screen is set as the primary display. 

**To Reproduce**
1. Connect an external monitor (In this pc, this will only work if the nvidia card is selected)
2. Make sure the notebook screen is the primary display
3. Change the screen brightness using the Fn keys

**Expected behavior**

The screen brightness level should be shown on the notebook screen.

**Screenshots**
[Video](https://youtu.be/l8zC5-xlvDs)

**Hardware and mintUpdate**

System:
  Kernel: 5.15.0-41-generic x86_64 bits: 64 compiler: gcc v: 11.2.0
    Desktop: Cinnamon 5.4.4 tk: GTK 3.24.33 vt: 7 dm: LightDM 1.30.0
    Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy
Machine:
  Type: Laptop System: Acer product: Nitro AN515-44 v: V1.04
    serial: <superuser required>
  Mobo: RO model: Stonic_RNS v: V1.04 serial: <superuser required>
    UEFI: Insyde v: 1.04 date: 02/04/2021
Battery:
  ID-1: BAT1 charge: 58.7 Wh (100.0%) condition: 58.7/58.8 Wh (99.8%)
    volts: 17.4 min: 15.4 model: SMP AP18E7M type: Li-ion serial: <filter>
    status: Full
  Device-1: hidpp_battery_0 model: Logitech Wireless Keyboard
    serial: <filter> charge: 55% (should be ignored) rechargeable: yes
    status: Discharging
  Device-2: hidpp_battery_1 model: Logitech Wireless Mouse serial: <filter>
    charge: 55% (should be ignored) rechargeable: yes status: Discharging
CPU:
  Info: 6-core model: AMD Ryzen 5 4600H with Radeon Graphics bits: 64
    type: MT MCP smt: enabled arch: Zen 2 rev: 1 cache: L1: 384 KiB L2: 3 MiB
    L3: 8 MiB
  Speed (MHz): avg: 1411 high: 1561 min/max: 1400/3000 boost: enabled
    cores: 1: 1397 2: 1397 3: 1561 4: 1406 5: 1397 6: 1397 7: 1397 8: 1397
    9: 1397 10: 1397 11: 1397 12: 1396 bogomips: 71863
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: NVIDIA TU117M vendor: Acer Incorporated ALI driver: nvidia
    v: 515.48.07 pcie: speed: 2.5 GT/s lanes: 8 ports: active: none
    off: HDMI-A-1 empty: none bus-ID: 01:00.0 chip-ID: 10de:1f99
    class-ID: 0300
  Device-2: AMD Renoir vendor: Acer Incorporated ALI driver: amdgpu
    v: kernel pcie: speed: 16 GT/s lanes: 16 ports: active: eDP-1 empty: none
    bus-ID: 05:00.0 chip-ID: 1002:1636 class-ID: 0300
  Device-3: Chicony HD User Facing type: USB driver: uvcvideo bus-ID: 3-3:3
    chip-ID: 04f2:b64f class-ID: 0e02 serial: <filter>
  Display: x11 server: X.Org v: 1.21.1.3 driver: X:
    loaded: amdgpu,ati,nvidia unloaded: fbdev,modesetting,nouveau,vesa
    gpu: amdgpu display-ID: :0 screens: 1
  Screen-1: 0 s-res: 3840x1080 s-dpi: 96 s-size: 1016x286mm (40.0x11.3")
    s-diag: 1055mm (41.6")
  Monitor-1: HDMI-0 pos: right res: 1920x1080 hz: 60 dpi: 102
    size: 477x268mm (18.8x10.6") diag: 547mm (21.5")
  Monitor-2: eDP-1-0 pos: primary,left res: 1920x1080 hz: 144 dpi: 142
    size: 344x194mm (13.5x7.6") diag: 395mm (15.5")
  OpenGL: renderer: NVIDIA GeForce GTX 1650/PCIe/SSE2
    v: 4.6.0 NVIDIA 515.48.07 direct render: Yes
Audio:
  Device-1: NVIDIA vendor: Acer Incorporated ALI driver: snd_hda_intel
    v: kernel pcie: speed: 8 GT/s lanes: 8 bus-ID: 01:00.1 chip-ID: 10de:10fa
    class-ID: 0403
  Device-2: AMD Raven/Raven2/FireFlight/Renoir Audio Processor
    vendor: Acer Incorporated ALI driver: N/A pcie: speed: 16 GT/s lanes: 16
    bus-ID: 05:00.5 chip-ID: 1022:15e2 class-ID: 0480
  Device-3: AMD Family 17h HD Audio vendor: Acer Incorporated ALI
    driver: snd_hda_intel v: kernel pcie: speed: 16 GT/s lanes: 16
    bus-ID: 05:00.6 chip-ID: 1022:15e3 class-ID: 0403
  Sound Server-1: ALSA v: k5.15.0-41-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Realtek vendor: Acer Incorporated ALI driver: r8169 v: kernel
    pcie: speed: 2.5 GT/s lanes: 1 port: 2000 bus-ID: 03:00.0
    chip-ID: 10ec:2600 class-ID: 0200
  IF: enp3s0 state: down mac: <filter>
  Device-2: Intel Wi-Fi 6 AX200 driver: iwlwifi v: kernel pcie:
    speed: 5 GT/s lanes: 1 bus-ID: 04:00.0 chip-ID: 8086:2723 class-ID: 0280
  IF: wlp4s0 state: up mac: <filter>
Bluetooth:
  Device-1: Intel AX200 Bluetooth type: USB driver: btusb v: 0.8
    bus-ID: 1-4:2 chip-ID: 8087:0029 class-ID: e001
  Report: hciconfig ID: hci0 rfk-id: 0 state: up address: <filter>
    bt-v: 3.0 lmp-v: 5.2 sub-v: 237e hci-v: 5.2 rev: 237e
Drives:
  Local Storage: total: 476.94 GiB used: 37.84 GiB (7.9%)
  ID-1: /dev/nvme0n1 vendor: Western Digital
    model: PC SN530 SDBPNPZ-512G-1014 size: 476.94 GiB speed: 31.6 Gb/s
    lanes: 4 type: SSD serial: <filter> rev: 21103900 temp: 40.9 C
    scheme: GPT
Partition:
  ID-1: / size: 467.89 GiB used: 37.83 GiB (8.1%) fs: ext4
    dev: /dev/nvme0n1p2
  ID-2: /boot/efi size: 511 MiB used: 5.2 MiB (1.0%) fs: vfat
    dev: /dev/nvme0n1p1
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 0 KiB (0.0%) priority: -2
    file: /swapfile
Sensors:
  System Temperatures: cpu: N/A mobo: N/A
  Fan Speeds (RPM): N/A
  GPU: device: nvidia screen: :0.0 temp: 40 C device: amdgpu temp: 38.0 C
Repos:
  Packages: apt: 2412
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/google-chrome.list
    1: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http://packages.linuxmint.com vanessa main upstream import backport
    2: deb http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
Info:
  Processes: 344 Uptime: 25m wakeups: 5 Memory: 15 GiB used: 2.45 GiB (16.4%)
  Init: systemd v: 249 runlevel: 5 Compilers: gcc: 11.2.0 alt: 11 Shell: Bash
  v: 5.1.16 running-in: gnome-terminal inxi: 3.3.13

**Additional context**

**Comment by clefebvre** [comment] 2022-07-22 12:30
Just noticed we show sound OSD on all monitors.

**Comment by JosephMcc** [comment] 2022-07-22 15:00
Prior to Cinnamon 5.4 the sound OSD was shown on all monitors and the brightness OSD was only supposed to show on the monitor where the brightness change was actually happening.

**Comment by mtwebster** [comment] 2022-07-23 01:43
It still should only be the monitor being changed.

Does this continue happening after you've restarted cinnamon? (or logged out and back in)

Can you run this while the problem is manifesting:
```
cinnamon-dbus-command GetMonitors
```
and paste the output.

Thanks

**Comment by clefebvre** [comment] 2022-07-23 10:33
> Prior to Cinnamon 5.4 the sound OSD was shown on all monitors and the brightness OSD was only supposed to show on the monitor where the brightness change was actually happening.

ah ok sorry, I wasn't aware this could be set per monitor.

**Comment by mantuoliveira** [comment] 2022-07-23 10:35
Restarting cinnamon has no effect, but rebooting the pc sometimes fixes/causes the issue. I will try to find a consistent way to reproduce it. Meanwhile, this is the output of the command you asked for:

<pre>Parsed: GetMonitors(format_string=&apos;()&apos;, args=[])

Returned: ([1, 0],)
</pre>

**Comment by mantuoliveira** [comment] 2022-07-23 11:03
I've found a way in which I can reproduce this all the time.

I have a hybrid notebook (amd and nvidia). When selecting "Power Saving Mode" I can't see anything on the external monitor. Selecting "Nvidia on-demand" results on both displays working and correct brightness OSD placement. However, selecting "Performance Mode" and rebooting the pc will always place the brightness OSD on the external monitor.

Not sure if this is intentional behavior or a another bug, but to go from NVIDIA only to NVIDIA on demand, one must use the "NVIDIA settings". The option is missing from the applet.

**Comment by mtwebster** [comment] 2022-07-23 11:27
That's a bug, it'll be fixed in the next update for that applet.

It seems like the system is mis-identifying which is the built-in monitor when you're in nvidia mode. Does the brightness adjustmant always work, and always the laptop monitor, regardless of prime mode, or where the osd shows up?

Can you provide the output to `xrandr --verbose` in both performance and on-demand mode? (Use dpaste.org or something because the output will be long).

**Comment by mantuoliveira** [comment] 2022-07-23 12:04
[on demand](https://dpaste.org/c8B9Z)
[performance mode](https://dpaste.org/gwYZt)

It works in both cases. No matter where the OSD is shown the laptop screen brightness is correctly adjusted.

**Closed as completed** 2022-07-24 11:58 UTC
Labels: Fixed in Git
