### ISSUE TITLE
parted: Cannot find hard drives to install

### ISSUE THREAD

**Issue by Xurel** [linuxmint/mint21-beta#26] opened 2022-07-14 21:08 UTC
I have 4 SSDs with 1 TB each. sda has a 500 MB EFI-partition, a 100 GB btrfs-Partition and the rest oft the drive plus the other 3 SSDs are configured as LVM with one 3.54 TB XFS-volume. When I open gparted it shows only USB-devices, but none of the SSDs. Same when I run the installer: only USB-devices to choose for installation. Mint 20.3 was installed with this configuration and worked flawlessly. Also Fedora and openSUSE could be installed without problems.

**Comment by clefebvre** [comment] 2022-07-23 12:31
Can the Mint 20.3 live ISO still see these partitions?

If so, then this could be a parted regression.

**Comment by ghost** [comment] 2022-07-23 13:20
Currently, Fedora 36 is installed on the system.
Mint 20.3 ISO can see all the drives and partitions. 21 beta just can see the usb-drive.

**Comment by clefebvre** [comment] 2022-07-23 13:49
@Xurel just to be sure this is down to parted. You can list the partitions with `sudo parted -l`.

If this works in 20.3 and not in 21 then there's likely a regression in parted between Ubuntu 20.04 and 22.04 (parted 3.3 and parted 3.4).

Can you confirm this is a parted bug? If so I'll close this and suggest to report this upstream https://www.gnu.org/software/parted/.

**Comment by ghost** [comment] 2022-07-23 14:33
Here is the output on both ISOs:

Mint 21
mint@mint:~$ sudo parted -l
Model: Samsung Flash Drive FIT (scsi)
Disk /dev/sda: 257GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start   End     Size    File system  Name       Flags
 1      32.8kB  2434MB  2434MB               ISO9660    hidden, msftdata
 2      2434MB  2438MB  4350kB               Appended2  boot, esp
 3      2439MB  257GB   254GB   ext4
 


Mint 20.3
mint@mint:~$ sudo parted -l
Model: ATA WDC WDS100T2B0A (scsi)
Disk /dev/sda: 1000GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start   End     Size   File system  Name                  Flags
 1      1049kB  630MB   629MB  fat32        EFI System Partition  boot, esp
 2      630MB   108GB   107GB  btrfs
 3      108GB   1000GB  892GB                                     lvm


Error: /dev/sdb: unrecognised disk label
Model: ATA WDC WDS100T2B0A (scsi)                                         
Disk /dev/sdb: 1000GB
Sector size (logical/physical): 512B/512B
Partition Table: unknown
Disk Flags: 

Error: /dev/sdc: unrecognised disk label
Model: ATA Samsung SSD 860 (scsi)                                         
Disk /dev/sdc: 1000GB
Sector size (logical/physical): 512B/512B
Partition Table: unknown
Disk Flags: 

Error: /dev/sdd: unrecognised disk label
Model: ATA WDC WDS100T2B0A (scsi)                                         
Disk /dev/sdd: 1000GB
Sector size (logical/physical): 512B/512B
Partition Table: unknown
Disk Flags: 

Warning: The driver descriptor says the physical block size is 2048 bytes, but
Linux says it is 512 bytes.
Ignore/Cancel? i                                                          
Model: Samsung Flash Drive FIT (scsi)
Disk /dev/sde: 1027GB
Sector size (logical/physical): 2048B/512B
Partition Table: mac
Disk Flags: 

Number  Start  End     Size    File system  Name   Flags
 1      2048B  6143B   4096B                Apple
 2      328kB  4424kB  4096kB               EFI


Model: Linux device-mapper (linear) (dm)
Disk /dev/mapper/terra-europa: 3893GB
Sector size (logical/physical): 512B/512B
Partition Table: loop
Disk Flags: 

Number  Start  End     Size    File system  Flags
 1      0.00B  3893GB  3893GB  xfs

**Comment by clefebvre** [comment] 2022-07-23 18:02
Thanks @Xurel, it looks like a parted regression. Please report it upstream directly.

**Closed by clefebvre** 2022-07-23 18:02 UTC
Labels: Need more info
