### ISSUE TITLE
[Cinnamon] When choosing an icon for a folder or file outside of the default icons, the wheel stays and does nothing

### ISSUE THREAD

**Issue by potocron** [linuxmint/mint21-beta#45] opened 2022-07-15 11:14 UTC
Hereś a video. If you try to choose an icon outside of the default theme on the system, the window where you choose the icons hangs, and does nothing
[mint21.webm](https://user-images.githubusercontent.com/109351106/179212338-476ebd13-9987-428f-a5ad-c844073a811a.webm)

**Comment by mtwebster** [comment] 2022-07-15 11:29
Duplicate of #9

**Closed by mtwebster** 2022-07-15 11:29 UTC
