### ISSUE TITLE
[Cinnamon] Xviewer disregards Plugin for "Disable Dark Theme"

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint21-beta#72] opened 2022-07-16 20:11 UTC
**Describe the bug**
When you first set [x] Disable Dark Theme in Preferences | Plugins tab, the dark theme changes to light immediately when checked.  Close Xviewer.  Open another image in Xviewer, the theme is dark.

**To Reproduce**
1. Open an image with Xviewer
2. Go to Preferences
3. Click on Plugins
4. Check  [x] Disable Dark Theme
5. Theme immediately changes to light.
6. Close Xviewer
7. Open Xviewer again.
8. Theme is dark but when you check Preferences | Plugins tab, [x] Disable Dark Theme is enabled.
9. Issue is solid and repeatable.

**Expected behavior**
Expected Xviewer to maintain the light theme as selected.

**Screenshots**
![Screenshot from 2022-07-16 16-00-48](https://user-images.githubusercontent.com/45599505/179370569-022eba58-fe81-47e8-a581-4d6f3132bcca.png)

Is your system all up-to-date ? Yes.

**Comment by JosephMcc** [comment] 2022-07-16 21:33
It seems to be ignoring the setting when you relaunch. Not sure if this is actually a new issue or not.

**Comment by JosephMcc** [comment] 2022-07-17 18:12
This one is an easy fix.

`apt install gir1.2-xviewer-3.0`

That needs to be installed by default for the xviewer plugins to work.

**Comment by Acheron17** [comment] 2022-07-17 18:42
So this will be done on the ISO or we would need to do it manually after a fresh install?

**Comment by Acheron17** [comment] 2022-07-17 18:56
Confirmed when this extra specified package is loaded the issue is resolved.

**Comment by JosephMcc** [comment] 2022-07-17 19:04
I'm unsure how the fix will be pushed out. Weather it will be done automatically by an update or some other means. I'm sure clem will let people know if they need to do something extra.

**Comment by Acheron17** [comment] 2022-07-17 19:08
Usually Clem would add the package to the ISO.  You may close this item out.  Thank you.

**Comment by JosephMcc** [comment] 2022-07-17 19:17
We are mostly leaving these open until we have a confirmed fix. Helps to make sure we don't let one slip through the cracks.

**Comment by clefebvre** [comment] 2022-07-18 12:09
Well, if the plugins don't work correctly without it, we can simply make it a dependency of xviewer-plugins.

**Closed as completed** 2022-07-20 06:04 UTC
Labels: Fixed in Git

**Comment by Acheron17** [comment] 2022-07-20 09:10
Update manager pulled in and installed the gir1.2-xviewer-3.0 package.  Issue was resolved.
