### ISSUE TITLE
[Mate] Can't change Menu button.

### ISSUE THREAD

**Issue by krash1220** [linuxmint/mint21-beta#59] opened 2022-07-15 22:54 UTC
Can't  change Mint Menu button to custom image. It just sits there saying Loading.... To get around it I had to rename the image I wanted to use and copy it to /usr/share/icons/highcolor/scalable/apps/linuxmint-logo-simple-symbolic.svg and that works fine.
![Screenshot at 2022-07-15 15-42-49](https://user-images.githubusercontent.com/10324887/179321664-3c994ef0-fba3-471b-9761-83d8912489d9.png)

**Comment by mtwebster** [comment] 2022-07-16 02:40
Duplicate of #9

**Closed by mtwebster** 2022-07-16 02:40 UTC
