### ISSUE TITLE
live: Consider disabling failed systemd services.

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint21-beta#3] opened 2022-07-14 14:32 UTC
Noted in all three Desktop Environments.

Issue:
journalctl logs showed failures for:

systemd[1]: Failed to start casper-md5check Verify Live ISO checksums.

systemd[1]: Failed to start LSB: disk temperature monitoring daemon.
hddtemp.service: Failed at step EXEC spawning /etc/init.d/hddtemp: No such file or directory

How to reproduce: boot the system and check journalctl

Expected behavior: Boot should be clean and free of errors.
If the service is going to fail why even start it?  If there is ever an upstream fix these services can be enabled in an update.

**Comment by SebastJava** [comment] 2022-07-18 00:09
I confirm this. I am seriously worried about this **disk temperature monitoring daemon.** It sounds really serious. I saw it on my VirtualBox and then restarted from a normal live USB key with LM 21. I got this confirmed from this live USB key. I don't have this error on Mint 20.3.

* [system-log-messages-from-live-USB-21.txt](https://github.com/linuxmint/mint21-beta/files/9128816/system-log-messages-from-live-USB-21.txt)
* [liveUSB_inxi -Fxxxrz.txt](https://github.com/linuxmint/mint21-beta/files/9128817/liveUSB_inxi.-Fxxxrz.txt)

**Comment by SebastJava** [comment] 2022-07-18 00:13
**Not just live !** Tested on both live USB 21 and on fully installed Mint 21 in VirtualBox.

**Comment by Acheron17** [comment] 2022-07-18 14:16
Just to see what is going on upstream booted into Ubuntu 22.04 live ISO and found the following:
casper-md5check.service runs to completion taking 57.436s

hddtemp.service is not present, started or running.
hddtemp package has to be installed for the systemd service which I do not see in the repository.
hddtemp package last showed in impish (21.10) (utils)

Still seeing SATA SSD temperatures with gnome-disk-utility. "Disk is OK (28° C / 82° F)"
So is hdtemp obsolete?

**Comment by SebastJava** [comment] 2022-07-18 14:55
> So is hdtemp obsolete?

I don't know. But let me explain what started me into this story. On booting, i noticed a brief 1/4 seconds "flash" of red text on this black background. It doesn't feels good. Being a 1/4 "flash", i had to do a video recording, from virtual machine, of course. To be able to read it. (!) And then i got it confirmed just by looking at the system logs. There, in the logs, click on it and you'll see this has "Priority 3". This means it gets **printed in red somewhere during boot sequence, for 1/4 seconds...**

![Logs-Failed-to-start-LSB](https://user-images.githubusercontent.com/31940713/179539664-51d758b1-1914-4e4b-b8f3-6e5d2ed959da.png)

**Additional context**
I am scared of taking a walk outside, and then come back and find my apartment is on fire because of this HDD... :(

**Comment by SebastJava** [comment] 2022-07-18 15:04
![celluloid-shot0001](https://user-images.githubusercontent.com/31940713/179541674-5775143f-87fa-4cf3-a9cf-4af2920fcd91.jpg)
red warning on boot sequence...

**Comment by Acheron17** [comment] 2022-07-18 15:05
hddtemp.service is running fine on LMDE 5 ... I just don't have the in depth knowledge to explain why it is not in LM 21 except the package is not present in Ubuntu 22.04.

**Comment by clefebvre** [comment] 2022-07-21 09:03
Fixed the hddtemp issue in ubuntu-system-adjustments. We no longer ship with it but we still referred to it.

For casper it's got to do with a delta between Mint and Ubuntu when it comes to the use of integrity check. It's a bit useless in its latest iteration so we stopped using it but it's still trying to be run in the background by casper. It's only cosmetic. We won't fix it in in 21.

**Closed by clefebvre** 2022-07-21 09:03 UTC
