### ISSUE TITLE
[Cinnamon] Pin to panel adds new panel launchers instead of adding to GWL

### ISSUE THREAD

**Issue by bwepstein** [linuxmint/mint21-beta#76] opened 2022-07-16 20:46 UTC
Cinnamon
Panel Icons
When clicking on add to panel, icon adds to tray of panel not the left side.
Happens for adding all icons.
Cannot change position or drag to left side.

**Comment by JosephMcc** [comment] 2022-07-16 21:12
Edited to fix the title

**Comment by mtwebster** [comment] 2022-07-16 21:16
duplicate of https://github.com/linuxmint/mint21-beta/issues/71 (fixed)

**Closed as completed by mtwebster** 2022-07-16 21:16 UTC
Labels: Duplicate

**Comment by bwepstein** [comment] 2022-07-17 09:28
Still not working. checked for all updates.
