### ISSUE TITLE
Cinnamon 5.4.4 Add To Panel issue

### ISSUE THREAD

**Issue by ooglaboogla** [linuxmint/mint21-beta#92] opened 2022-07-17 17:37 UTC
By default, Mint has long used the Grouped Window List instead of Panel Launchers Applet, for the "Modern" look. That hasn't changed, but there is a new bug in Cinnamon 5.4.4 that wasn't there in 5.4.2. I was running Mint 21 Dev before Mint 21 Beta was released, and with Cinnamon 5.4.2, I was completely able to add applications to the Grouped Window List by using the right-click option in the Cinnamon Menu for Add To Panel. Now on Cinnamon 5.4.4 in the Beta, when I try to do this, Panel Launchers is added to the tray, and that's where the application is added. I tried this on the Dev installation as well, which I assume is the same as the Beta now, and the same thing happened. I even opened the Mint Welcome window and chose the Modern look option, removed the Panel Launchers Applet, then restarted. Still did the same thing. No longer able to add applications to the Grouped Window List using Add To Panel. If I open an application and right-click its icon in the Grouped Window List, choosing Pin To Panel still works to add it.

**Comment by JosephMcc** [comment] 2022-07-17 18:04
This is a duplicate of https://github.com/linuxmint/mint21-beta/issues/71

**Closed as completed by JosephMcc** 2022-07-17 18:04 UTC
Labels: Duplicate

**Comment by ooglaboogla** [comment] 2022-07-17 18:16
While this may be a duplicate, I must point out that I am running the absolute latest updates on Mint 21 Beta and Mint 21 Dev, and it is definitely not fixed. On Cinnamon 5.4.2 on ArcoLinuxB Cinnamon, it still works correctly. Before upgrading Cinnamon to 5.4.4 on Mint 21, it worked correctly. I'm done here. Good luck with Mint 21.

**Comment by JosephMcc** [comment] 2022-07-17 18:19
The fix hasn't been released on Mint yet. That's why the other issue is still open.
